final List<String> city = [
  'Kuala Lumpur',
  'Klang',
  'Ipoh',
  'Butterworth',
  'George Town',
  'Petaling Jaya',
  'Kuantan',
  'Shah Alam',
  'Johor Bahru',
  'Kota Bharu',
  'Melaka',
  'Kota Kinabalu',
  'Seremban',
  'Sandakan',
  'Sungai Petani',
  'Kuching',
  'Kuala Terengganu',
  'Alor Setar',
  'Putrajaya',
  'Kangar',
  'Labuan',
  'Pasir Mas',
  'Tumpat',
  'Ketereh',
  'Kampung Lemal',
  'Pulai Chondong'
];
